Module2 task1
htmlacademy-ecmascript/537493-cinemaddict-13 pull request #5
Opened 2020-12-07 20:53 UTC by Feldbush

2020-12-09 14:46 UTC, DmitryMarkov requested changes
Пункты ДЗ в целом выполнены, но есть довольно много замечаний

2020-12-09 14:46 UTC, DmitryMarkov commented on package.json
> +    "dayjs": "1.9.5",
надо перенести в обычные зависимости, потому что devDependencies нужны для разработки, а обычные - это то, что используется в самом коде проекта (через импорты)

2020-12-09 14:46 UTC, DmitryMarkov commented on src/main.js
> +// import dayjs from 'dayjs';
комменты кода запрещены

2020-12-09 14:46 UTC, DmitryMarkov commented on src/main.js
> +const filmsMockData = new Array(15).fill().map((item, index) => createMockFilmCard(index));
лучше генерацию моков вынести в отдельный файл и его просто импортировать сюда

2020-12-09 14:46 UTC, DmitryMarkov commented on src/mock/film.js
> +} from '../utils.js';
расширение `js` можно не указывать при импортах

```suggestion
} from '../utils';
```

2020-12-09 14:46 UTC, DmitryMarkov commented on src/mock/film.js
> +// console.log(getRandomElementsArray(DESCRIPTIONS));
комменты кода 🚫

2020-12-09 14:46 UTC, DmitryMarkov commented on src/mock/film.js
> +    isInFavorite: Boolean(getRandomInteger(0, 1))
Можно не передавать, раз они у тебя реализованы в функции как значения по умолчанию. Но, с другой стороны, явное лучше не явного 🤷 
```suggestion
    isInWatchList: Boolean(getRandomInteger()),
    isInHistory: Boolean(getRandomInteger()),
    isInFavorite: Boolean(getRandomInteger())
```

2020-12-09 14:46 UTC, DmitryMarkov commented on src/utils.js
> +  const quantityTry = maxQuantityTry;
неясно зачем присваивание внутренней переменной и не использовать аргумент функции

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-card.js
>      <button class="film-card__controls-item button film-card__controls-item--add-to-watchlist" type="button">Add to watchlist</button>
надо также использовать `--active` класс согласно данным из объекта фильма

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-card.js
> +  <a class="film-card__comments">${comments.length} ${comments.length >= 2 ? `comments` : `comment`}</a>
обычно стараются использовать более простые сравнения, семантический смысл от этого не меняется

```suggestion
  <a class="film-card__comments">${comments.length} ${comments.length > 1 ? `comments` : `comment`}</a>
```

2020-12-09 14:46 UTC, DmitryMarkov commented on src/mock/film.js
> +    genre: getRandomElementsArray(GENRE),
название переменной надо поменять, genre подразумевает единичный элемент, а у тебя массив

2020-12-09 14:46 UTC, DmitryMarkov commented on src/mock/film.js
> +    director: getRandomArrayElement(DIRECTORS),
а что если у нас несколько режиссеров?

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +    })
выглядит, конечно, избыточно, но пока оставим, так как логика все равно будет изменена при получении данных с сервера

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +        <span class="film-details__comment-day">2 days ago</span>
хардкод, надо брать генерить и эти данные тоже в моках

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +      <img src="./images/emoji/sleeping.png" width="55" height="55" alt="emoji-sleeping">
эмоджи тоже выбирать из списка

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
>            <p class="film-details__age">18+</p>
тоже моковые данные

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +              <td class="film-details__cell">${writerts.length > 0 ? writerts.join(`, `) : writerts}</td>
у фильма не может не быть сценаристов, зачем эта проверка?

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +    writerts,
```suggestion
    writers,
```

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +              <td class="film-details__cell">${actors.length > 0 ? actors.join(`, `) : actors}</td>
то же с актерами. не оченб понятен тип данных. Он может быть массивом и строкой? Тогда проверка неверная, у строки тоже есть свойство `length`

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
> +          ${commentsHTML}
```suggestion
          ${commentsTemplate}
```

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/film-details.js
>        </div>
Watched/Favorite статус тоже надо брать из моков

2020-12-09 14:46 UTC, DmitryMarkov commented on src/view/menu.js
> +    ${filtersHtml}
```suggestion
    ${filtersTemplate}
```

2020-12-09 18:29 UTC, Feldbush commented on src/view/film-details.js
> +              <td class="film-details__cell">${actors.length > 0 ? actors.join(`, `) : actors}</td>
Здесь всегда прилетает массив, если его длинна больше чем 1 я записваю актёров через запятую

2020-12-09 18:33 UTC, Feldbush commented on src/mock/film.js
> +    isInFavorite: Boolean(getRandomInteger(0, 1))
Оставим явно)

2020-12-09 18:37 UTC, Feldbush commented on src/mock/film.js
> +    director: getRandomArrayElement(DIRECTORS),
В ТЗ указан один)

2020-12-09 18:40 UTC, Feldbush commented on src/view/film-details.js
> +              <td class="film-details__cell">${actors.length > 0 ? actors.join(`, `) : actors}</td>
Исправил на `actors.length > 1`

2020-12-10 05:57 UTC, Feldbush commented on src/view/film-details.js
> +              <td class="film-details__cell">${writerts.length > 0 ? writerts.join(`, `) : writerts}</td>
Здесь всегда прилетает массив, если его длинна больше чем 1 я записваю актёров через запятую

2020-12-10 12:07 UTC, DmitryMarkov requested changes
Замечания исправлены, но осталось еще немного :)

2020-12-10 12:07 UTC, DmitryMarkov commented on src/mock/film.js
>  const RELEASE_DATE = [`30 March`, `11 March`, `10 March`];
Здесь тоже лучше использовать timestamp или dateString и форматировать в шаблоне

2020-12-10 12:07 UTC, DmitryMarkov commented on src/mock/film.js
> +    director: getRandomArrayElement(DIRECTORS),
Принимается :)

2020-12-10 12:07 UTC, DmitryMarkov commented on src/view/film-details.js
> +    return prev + ` ` + `<span class="film-details__genres">${item}</span>`;
мы не используем конкатенацию для строк, используй переменные в шаблонных строках

2020-12-10 12:07 UTC, DmitryMarkov commented on src/mock/film.js
> +    age: getRandomArrayElement(AGES)
я бы назвал более специфично:
```suggestion
    minAge: getRandomArrayElement(AGES)
```

2020-12-10 12:07 UTC, DmitryMarkov commented on src/view/film-details.js
> +              <td class="film-details__term">${genres.length > 1 ? `genress` : `genres`}</td>
```suggestion
              <td class="film-details__term">${genres.length > 1 ? `genres` : `genres`}</td>
```

2020-12-10 12:07 UTC, DmitryMarkov commented on src/view/film-details.js
> +              <td class="film-details__cell">${writers.length > 1 ? writers.join(`, `) : writers}</td>
выводить массив в разметку не круто. Сделай приведение к строке, хотя бы так:

```suggestion
              <td class="film-details__cell">${writers.length > 1 ? writers.join(`, `) : writers.join(``)}</td>
```

2020-12-11 10:26 UTC, DmitryMarkov approved these changes
Замечания исправлены, всё отлично, продолжаем! 💪

2020-12-11 10:26 UTC, merged